// Code generated by constgen. DO NOT EDIT.
package output

const (
	DebianBookworm         = "debian:bookworm"
	Golang121Bookworm      = "golang:1.21.5-bookworm"
	Postgres15Alpine       = "postgres:15-alpine"
	Postgres16Alpine       = "postgres:16-alpine"
	Postgres16Alpine_1     = "postgres-16-alpine"
	Postgres16Alpine_2     = "!@#postgres-16-alpine"
	C123Postgres16Alpine   = "123postgres-16-alpine"
	C123Postgres16Alpine_1 = "!_@123postgres-16-alpine"
	Vault113               = "vault:1.13.3"
	Vault113_1             = "vault:1.:@$-!13.3"
	Redis723Alpine         = "redis:7.2.3-alpine"
	C123                   = "1231231737127"
	DebianBookwormDebian   = "debian:bookworm:debian:bookworm:debian:bookworm:debian:bookworm:debian:bookworm:"
)
